server {
    listen 80;
    resolver 127.0.0.11 valid=10s;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~ ^/(auth|targets|tweets|analysis|alerts|twitter|tasks|health|rag|monitoring|mlflow|data)/ {
        proxy_pass http://api:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location ~ ^/(auth|targets|tweets|analysis|alerts|twitter|tasks|health|rag|monitoring|mlflow|data)$ {
        proxy_pass http://api:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
